export const MAX_MIGRATION_ARTIFACT_BYTES = 16 * 1024 * 1024;
export const MAX_MIGRATION_USERS = 10_000;
export const MAX_MIGRATION_CHARACTERS = 10_000;
export const MAX_MIGRATION_MEMBERSHIPS = 20_000;
export const MAX_MIGRATION_ISSUES = 1_000;
export const MAX_MIGRATION_CURRENCIES = 32;
export const MAX_MIGRATION_METADATA_MAPPINGS = 64;
export const MAX_MIGRATION_METADATA_VALUES =
  MAX_MIGRATION_CHARACTERS * MAX_MIGRATION_METADATA_MAPPINGS;
