export function worldBundleFixture(): Record<string, unknown> {
  return {
    schema: 1,
    key: "synex_fixture:base",
    version: "1.0.0",
    dependencies: ["map_fixture"],
    objects: [
      {
        kind: "region",
        key: "synex_fixture:city",
        label: "Fixture City",
        tags: ["world.fixture"],
        geometry: {
          type: "aabb",
          min: { x: -100, y: -100, z: -20 },
          max: { x: 100, y: 100, z: 100 },
        },
      },
      {
        kind: "location",
        key: "synex_fixture:station",
        parent: "synex_fixture:city",
        mapPackages: ["synex_fixture:map"],
        iplBundles: ["synex_fixture:ipls"],
        geometry: { type: "sphere", center: { x: 0, y: 0, z: 10 }, radius: 40 },
      },
      {
        kind: "interior",
        key: "synex_fixture:station_interior",
        parent: "synex_fixture:station",
        geometry: {
          type: "box",
          center: { x: 0, y: 0, z: 10 },
          size: { x: 30, y: 20, z: 10 },
          heading: 25,
        },
      },
      {
        kind: "room",
        key: "synex_fixture:lobby",
        parent: "synex_fixture:station_interior",
        geometry: {
          type: "aabb",
          min: { x: -10, y: -8, z: 5 },
          max: { x: 10, y: 8, z: 15 },
        },
      },
      {
        kind: "zone",
        key: "synex_fixture:counter_zone",
        parent: "synex_fixture:lobby",
        geometry: {
          type: "polygon",
          vertices: [{ x: -4, y: -2 }, { x: 4, y: -2 }, { x: 4, y: 2 }, { x: -4, y: 2 }],
          minZ: 5,
          maxZ: 15,
        },
      },
      {
        kind: "anchor",
        key: "synex_fixture:counter",
        parent: "synex_fixture:counter_zone",
        position: { x: 0, y: 0, z: 10 },
        radius: 2,
        entityRef: { entityId: "fixture_counter", generation: 1 },
      },
      {
        kind: "door",
        key: "synex_fixture:lobby_door",
        parent: "synex_fixture:lobby",
        position: { x: 0, y: -8, z: 10 },
        leaves: [{ id: "main", model: 1234, position: { x: 0, y: -8, z: 10 }, heading: 0 }],
        defaultState: "LOCKED",
        persistent: true,
        accessPolicy: { requiredCapability: "synex.world.enter", groupId: "GROUP-01" },
        autoRelockSeconds: 10,
      },
      {
        kind: "portal",
        key: "synex_fixture:entry",
        parent: "synex_fixture:station",
        portalType: "teleport",
        source: { position: { x: 0, y: -20, z: 10 }, radius: 2 },
        destination: { position: { x: 0, y: 0, z: 10 }, heading: 0 },
        enabled: true,
      },
      {
        kind: "portal",
        key: "synex_fixture:exit",
        parent: "synex_fixture:lobby",
        portalType: "physical",
        source: { position: { x: 0, y: 7, z: 10 }, radius: 2 },
        destination: { target: "synex_fixture:station" },
      },
      {
        kind: "instance_template",
        key: "synex_fixture:training_instance",
        baseLocation: "synex_fixture:station",
        entry: { x: 0, y: 0, z: 10 },
        exit: { x: 0, y: -20, z: 10 },
        capacity: 16,
        ttlSeconds: 3600,
        isolationProfile: "isolated_strict",
        cleanupPolicy: "empty_ttl",
      },
      {
        kind: "portal",
        key: "synex_fixture:instance_entry",
        parent: "synex_fixture:station",
        portalType: "instance",
        source: { position: { x: 10, y: 0, z: 10 }, radius: 2 },
        destination: { instanceTemplate: "synex_fixture:training_instance" },
      },
      {
        kind: "map_package",
        key: "synex_fixture:map",
        resourceName: "map_fixture",
        packageType: "mlo",
        expectedResourceState: "started",
        version: "1.0.0",
        locations: ["synex_fixture:station"],
        iplBundles: ["synex_fixture:ipls"],
      },
      {
        kind: "ipl_bundle",
        key: "synex_fixture:ipls",
        mapPackages: ["synex_fixture:map"],
        ipls: ["fixture_station_ipl"],
        scope: "context",
        interiorSets: [{ interiorId: 1, name: "fixture_set" }],
      },
      {
        kind: "world_state_definition",
        key: "synex_fixture:alarm_state",
        parent: "synex_fixture:lobby",
        stateType: "boolean",
        scope: "room",
        persistence: "persistent",
        schemaVersion: 1,
        default: false,
      },
    ],
  };
}
