local function consumer()
    local resource = GetInvokingResource()
    if type(resource) ~= 'string' or #resource < 2 or #resource > 64
        or not resource:match('^[A-Za-z0-9][A-Za-z0-9_.%-]*$') then
        return nil
    end
    return resource
end

local function call(name, ...)
    local caller = consumer()
    if not caller then return nil end
    return exports.synex_bridge_qbx[name](caller, ...)
end

exports('GetPlayer', function(playerSource)
    return call('GetPlayerForConsumer', playerSource)
end)
exports('GetPlayerByCitizenId', function(citizenId)
    return call('GetPlayerByCitizenIdForConsumer', citizenId)
end)
exports('GetOfflinePlayer', function(citizenId)
    return call('GetOfflinePlayerForConsumer', citizenId)
end)
exports('GetMoney', function(identifier, moneyType)
    return call('GetMoneyForConsumer', identifier, moneyType)
end)
exports('AddMoney', function(identifier, moneyType, amount, reason)
    return call('AddMoneyForConsumer', identifier, moneyType, amount, reason)
end)
exports('RemoveMoney', function(identifier, moneyType, amount, reason)
    return call('RemoveMoneyForConsumer', identifier, moneyType, amount, reason)
end)
exports('SetMoney', function(identifier, moneyType, amount, reason)
    return call('SetMoneyForConsumer', identifier, moneyType, amount, reason)
end)
exports('GetMetadata', function(identifier, key)
    return call('GetMetadataForConsumer', identifier, key)
end)
exports('SetMetadata', function(identifier, key, value)
    return call('SetMetadataForConsumer', identifier, key, value)
end)
exports('GetGroups', function(playerSource)
    return call('GetGroupsForConsumer', playerSource)
end)
exports('HasGroup', function(playerSource, filter)
    return call('HasGroupForConsumer', playerSource, filter)
end)
exports('HasPrimaryGroup', function(playerSource, filter)
    return call('HasPrimaryGroupForConsumer', playerSource, filter)
end)
exports('SetPlayerPrimaryJob', function(citizenId, jobName)
    return call('SetPlayerPrimaryJobForConsumer', citizenId, jobName)
end)
exports('SetPlayerPrimaryGang', function(citizenId, gangName)
    return call('SetPlayerPrimaryGangForConsumer', citizenId, gangName)
end)
exports('SetJob', function(identifier, jobName, grade)
    return call('SetJobForConsumer', identifier, jobName, grade)
end)
exports('SetGang', function(identifier, gangName, grade)
    return call('SetGangForConsumer', identifier, gangName, grade)
end)
exports('SetJobDuty', function(identifier, onDuty)
    return call('SetJobDutyForConsumer', identifier, onDuty)
end)
