SynexNotifyLimits = {
    schemaVersion = 1,
    apiVersion = '1.0.0',
    maximumSafeInteger = 9007199254740991,
    maximumPlayerSource = 65535,
    maximumNotificationIdBytes = 96,
    maximumResourceNameBytes = 64,
    maximumSessionIdBytes = 64,
    maximumTitleBytes = 120,
    maximumMessageBytes = 720,
    maximumActionIdBytes = 64,
    maximumActionTokenBytes = 96,
    maximumActionLabelBytes = 64,
    maximumActionHintBytes = 24,
    maximumDedupeKeyBytes = 96,
    maximumGroupKeyBytes = 96,
    defaultMaxRefreshCount = 4,
    maximumRefreshCount = 32,
    maximumActions = 2,
    maximumActionTokens = 512,
    maximumQueue = 128,
    maximumVisible = 4,
    maximumHistory = 128,
    maximumServerNotifications = 512,
    maximumOwnerNotifications = 256,
    maximumSendMany = 32,
    maximumBroadcastTargets = 256,
    maximumPayloadBytes = 4096,
    maximumCount = 9999,
    minimumDurationMs = 1500,
    defaultDurationMs = 5000,
    durationBaseMs = 2800,
    durationPerCharacterMs = 32,
    durationPriorityBonusMs = {
        low = 0,
        normal = 500,
        high = 1500,
        critical = 2500,
    },
    durationKindBonusMs = {
        toast = 0,
        status = 1000,
        banner = 2500,
    },
    maximumDurationMs = 30000,
    minimumDurationScale = 50,
    maximumDurationScale = 200,
    minimumSoundVolume = 0,
    maximumSoundVolume = 100,
    minimumLifetimeMs = 3000,
    maximumLifetimeMs = 120000,
    terminalDurationMs = 4000,
    minimumActionTtlMs = 1000,
    defaultActionTtlMs = 10000,
    maximumActionTtlMs = 30000,
    progressCoalesceMs = 100,
    dedupeWindowMs = 2000,
    groupingWindowMs = 2000,
    burstWindowMs = 1000,
    maximumBurst = 8,
    starvationStepMs = 4000,
    timerMaximumDelayMs = 30000,
    soundMinimumIntervalMs = 1500,
    actionMinimumIntervalMs = 250,
    uiVisibilityAckTimeoutMs = 1250,
    maximumRecentCommands = 256,
    maximumPendingCommands = 1024,
    maximumPendingCommandsPerSource = 128,
    pendingCommandTtlMs = 10000,
    maximumPendingWakes = 64,
    commandPullTimeoutMs = 3000,
    maximumCommandPullAttempts = 3,
    commandPullRetryDelayMs = 250,
    commandPullBudgetCapacity = 32,
    commandPullBudgetRefillPerSecond = 16,
    metricsInitialReportDelayMs = 0,
    metricsBaselineRetryDelayMs = 1000,
    maximumMetricsBaselineRetries = 5,
    metricsReportIntervalMs = 10000,
    metricsReportTimeoutMs = 3000,
    metricsMinimumReportIntervalMs = 5000,
    metricsFreshnessMs = 30000,
    metricsMaximumCounter = 1000000000000,
    metricsMaximumCounterDelta = 512,
    metricsMaximumEpochAdvances = 3,
    metricsEpochAdvanceWindowMs = 60000,
    maximumClientMetricSessions = 512,
    ownerBudgetCapacity = 24,
    ownerBudgetRefillPerSecond = 6,
    updateBudgetCapacity = 48,
    updateBudgetRefillPerSecond = 16,
    globalBudgetCapacity = 64,
    globalBudgetRefillPerSecond = 20,
    actionBudgetCapacity = 8,
    actionBudgetRefillPerSecond = 2,
    rateLimits = {
        global = { capacity = 64, refillPerSecond = 20 },
        owner = { capacity = 24, refillPerSecond = 6 },
        update = { capacity = 48, refillPerSecond = 16 },
        toast = { capacity = 18, refillPerSecond = 6 },
        progress = { capacity = 8, refillPerSecond = 2 },
        persistent = { capacity = 4, refillPerSecond = 0.5 },
        banner = { capacity = 2, refillPerSecond = 0.1 },
        status = { capacity = 12, refillPerSecond = 4 },
        high = { capacity = 6, refillPerSecond = 1 },
        critical = { capacity = 2, refillPerSecond = 0.1 },
        action = { capacity = 8, refillPerSecond = 2 },
        command_pull = { capacity = 32, refillPerSecond = 16 },
        metrics_report = { capacity = 2, refillPerSecond = 0.2 },
    },
    notificationCosts = {
        toast = 1,
        progress = 2,
        persistent = 3,
        banner = 6,
        status = 1,
        low = 1,
        normal = 1,
        high = 2,
        critical = 4,
    },
    kinds = {
        toast = true,
        progress = true,
        persistent = true,
        banner = true,
        status = true,
    },
    tones = {
        neutral = true,
        info = true,
        success = true,
        warning = true,
        danger = true,
    },
    priorities = {
        low = true,
        normal = true,
        high = true,
        critical = true,
    },
    positions = {
        ['top-right'] = true,
        ['top-left'] = true,
        ['bottom-right'] = true,
        ['bottom-left'] = true,
        ['top-center'] = true,
        ['bottom-center'] = true,
    },
    progressStates = {
        PENDING = true,
        RUNNING = true,
        SUCCESS = true,
        FAILED = true,
        CANCELLED = true,
    },
    terminalProgressStates = {
        SUCCESS = true,
        FAILED = true,
        CANCELLED = true,
    },
    progressModes = {
        determinate = true,
        indeterminate = true,
    },
    actionStyles = {
        primary = true,
        quiet = true,
        danger = true,
    },
    uiActionStyles = {
        default = true,
        primary = true,
        danger = true,
    },
    dedupePolicies = {
        suppress = true,
        count = true,
        replace = true,
        refresh = true,
    },
    dismissReasons = {
        dismissed = true,
        cancelled = true,
        superseded = true,
        expired = true,
        owner_stopped = true,
        queue_evicted = true,
    },
    iconKeys = {
        check = true,
        close = true,
        ['chevron-down'] = true,
        ['chevron-right'] = true,
        ['arrow-left'] = true,
        ['arrow-right'] = true,
        search = true,
        plus = true,
        minus = true,
        more = true,
        copy = true,
        eye = true,
        ['eye-off'] = true,
        info = true,
        warning = true,
        error = true,
        success = true,
        menu = true,
        command = true,
        signal = true,
    },
}
