SynexSecurityLimits = {
    schemaVersion = 1,
    apiVersion = '1.0.0',
    maximumSafeInteger = 9007199254740991,
    maximumPlayerSource = 65535,
    maximumResourceNameBytes = 64,
    maximumIdentifierBytes = 64,
    minimumCoreAccessIdBytes = 8,
    maximumCoreAccessIdBytes = 36,
    maximumNamespaceBytes = 96,
    maximumCodeBytes = 64,
    maximumSummaryBytes = 192,
    maximumReasonBytes = 320,
    minimumTemporaryBanDurationMs = 60000,
    minimumTemporaryBanRemainingMs = 30000,
    maximumEvidenceBytes = 4096,
    maximumEvidenceDepth = 6,
    maximumEvidenceEntries = 64,
    maximumEvidenceStringBytes = 512,
    maximumSignalBytes = 8192,
    maximumSignalBuffer = 4096,
    maximumSubjectSignals = 256,
    signalRetentionMs = 3600000,
    signalDedupeWindowMs = 5000,
    maximumExpectations = 4096,
    maximumOwnerExpectations = 256,
    minimumExpectationTtlMs = 100,
    defaultExpectationTtlMs = 15000,
    maximumExpectationTtlMs = 300000,
    maximumExpectationSelectors = 32,
    maximumCorrelationSignals = 256,
    maximumHypotheses = 16,
    maximumCorrelationBuffer = 8192,
    maximumCases = 4096,
    maximumClosedCaseArchive = 256,
    maximumCaseSignals = 32,
    maximumCaseEvidenceClasses = 8,
    maximumEnforcementHistory = 2048,
    enforcementIdempotencyRetentionMs = 86400000,
    minimumCaseConfidence = 0.42,
    minimumReviewConfidence = 0.58,
    confidencePrecision = 10000,
    categories = {
        transport = true,
        economy = true,
        inventory = true,
        interaction = true,
        movement = true,
        combat = true,
        player_integrity = true,
        entity = true,
        weapon = true,
        world = true,
        client_integrity = true,
        resource_integrity = true,
        connection = true,
    },
    evidenceClasses = {
        SERVER_AUTHORITATIVE = true,
        DOMAIN_AUTHORITATIVE = true,
        SERVER_DERIVED = true,
        CFX_SERVER_EVENT = true,
        CLIENT_TELEMETRY = true,
        BEHAVIORAL_HEURISTIC = true,
    },
    expectationKinds = {
        ['combat.invulnerable'] = true,
        ['combat.passive'] = true,
        ['visibility.hidden'] = true,
        ['movement.teleport'] = true,
        ['movement.noclip'] = true,
        ['camera.spectate'] = true,
        ['camera.freecam'] = true,
        ['player.model'] = true,
        ['weapon.grant'] = true,
        ['entity.spawn'] = true,
    },
    expectationKindCategories = {
        ['combat.invulnerable'] = { combat = true, player_integrity = true },
        ['combat.passive'] = { combat = true, player_integrity = true },
        ['visibility.hidden'] = { player_integrity = true },
        ['movement.teleport'] = { movement = true },
        ['movement.noclip'] = { movement = true },
        ['camera.spectate'] = { movement = true, player_integrity = true },
        ['camera.freecam'] = { movement = true, player_integrity = true },
        ['player.model'] = { player_integrity = true },
        ['weapon.grant'] = { weapon = true },
        ['entity.spawn'] = { entity = true },
    },
    evidenceWeights = {
        SERVER_AUTHORITATIVE = 1.00,
        DOMAIN_AUTHORITATIVE = 0.90,
        SERVER_DERIVED = 0.75,
        CFX_SERVER_EVENT = 0.80,
        CLIENT_TELEMETRY = 0.25,
        BEHAVIORAL_HEURISTIC = 0.35,
    },
    weakEvidenceClasses = {
        CLIENT_TELEMETRY = true,
        BEHAVIORAL_HEURISTIC = true,
    },
    severities = {
        INFO = true,
        LOW = true,
        MEDIUM = true,
        HIGH = true,
        CRITICAL = true,
    },
    severityRanks = {
        INFO = 1,
        LOW = 2,
        MEDIUM = 3,
        HIGH = 4,
        CRITICAL = 5,
    },
    severityWeights = {
        INFO = 0.10,
        LOW = 0.25,
        MEDIUM = 0.50,
        HIGH = 0.75,
        CRITICAL = 1.00,
    },
    detectorModes = {
        DISABLED = true,
        OBSERVE = true,
        MITIGATE = true,
        ENFORCE = true,
    },
    caseStates = {
        OPEN = true,
        MONITORING = true,
        REVIEW = true,
        ENFORCED = true,
        CLOSED = true,
    },
    enforcementActions = {
        OBSERVE = true,
        CORRECT = true,
        MITIGATE = true,
        RESTRICT = true,
        KICK = true,
        BAN = true,
        MANUAL_REVIEW = true,
    },
    enforcementRanks = {
        OBSERVE = 1,
        CORRECT = 2,
        MITIGATE = 3,
        RESTRICT = 4,
        KICK = 5,
        BAN = 6,
        MANUAL_REVIEW = 1,
    },
    categoryWindowsMs = {
        transport = 30000,
        economy = 120000,
        inventory = 120000,
        interaction = 60000,
        movement = 90000,
        combat = 300000,
        player_integrity = 120000,
        entity = 30000,
        weapon = 120000,
        world = 60000,
        client_integrity = 120000,
        resource_integrity = 300000,
        connection = 120000,
    },
}
